#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Test a local genuine checkout in a fresh private clone; record real commit IDs.

Requires network for that checkout's normal bootstrap unless pre-provisioned.
--base-sif adds Container generation; --run adds REAL Apptainer execution.
Without those flags the report explicitly marks container stages NOT RUN.
"""
import argparse
import json
import hashlib
import math
from collections import Counter
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import yaml
from configure_examples import create_config
from patch_core import make_patch

ROOT=Path(__file__).resolve().parents[1]


def normal(value):
    if isinstance(value,dict):
        return {k:normal(v) for k,v in value.items() if k not in ('benchpark_experiment_command','destdir')}
    if isinstance(value,list):return [normal(v) for v in value]
    return value


def require_completed_attempts(paths, minimum=4):
    """Count and validate real attempts; new-but-failed CER is not success."""
    paths = list(paths)
    if len(paths) < minimum:
        raise RuntimeError('Expected at least %d concrete CER records, got %d' % (minimum, len(paths)))
    failed = [str(p) for p in paths if json.loads(Path(p).read_text())['status'] != 'COMPLETED']
    if failed:
        raise RuntimeError('At least one actual attempt failed; see ' + failed[0])



def verify_installed_source(root):
    """Check the runtime AND relocated host integration before any bootstrap.

    Loading an old integration broker with a new Container module is not a
    successful test of this checkout. No package is installed implicitly here.
    """
    import importlib
    import importlib.metadata
    modules = {name: importlib.import_module(name) for name in
               ('benchpark_container', 'benchpark_integration', 'benchpark_tuning')}
    version = importlib.metadata.version('benchpark-container-extension')
    if version != modules['benchpark_container'].__version__:
        raise RuntimeError('Imported module and installed metadata versions differ')
    mismatches, origins = [], {}
    for name, module in modules.items():
        imported = Path(module.__file__).resolve().parent
        source = Path(root) / 'src' / name
        origins[name] = str(imported)
        for file in sorted(source.rglob('*')):
            if file.is_file() and '__pycache__' not in file.parts and file.suffix not in ('.pyc', '.pyo'):
                other = imported / file.relative_to(source)
                if not other.is_file() or hashlib.sha256(file.read_bytes()).digest() != hashlib.sha256(other.read_bytes()).digest():
                    mismatches.append(name + '/' + str(file.relative_to(source)))
    if mismatches:
        raise RuntimeError('Installed extension does not match this tool source: ' + ', '.join(mismatches[:8]))
    return {'version': version, 'module_origin': origins['benchpark_container'],
            'integration_origins': origins, 'tool_root': str(Path(root).resolve()),
            'host_python': sys.executable, 'host_python_version': sys.version, 'source_match': 'passed'}


def _runnable_concrete_plan(plan):
    """Return False for Ramble's repeat-base aggregation experiment.

    Ramble renders one repeat base plus n repeat children when n_repeats > 0,
    but ExecutePipeline intentionally skips the repeat base. New adapters avoid
    staging a concrete plan for it; this predicate also makes verification
    defensive for workspaces generated by an older adapter in the same run.
    """
    repeat = str(plan.get('repeat_index', 'unknown'))
    raw = plan.get('parameters', {}).get('n_repeats', '0')
    try:
        n_repeats = int(raw)
    except (TypeError, ValueError):
        raise RuntimeError('Invalid n_repeats in concrete plan: '+repr(raw))
    return not (n_repeats > 0 and repeat in ('unknown', 'None', ''))


def planned_attempts(workspace):
    all_plans=[json.loads(p.read_text()) for p in sorted((Path(workspace)/'.benchpark-extensions/concrete').glob('*.json'))]
    plans=[p for p in all_plans if _runnable_concrete_plan(p)]
    pairs={(str(p['parameters']['model']),str(p['parameters']['size'])) for p in plans}
    if pairs!={(m,n) for m in ('linear','mlp') for n in ('16','32')}:
        raise RuntimeError('Ramble runnable concrete plan omitted/unexpected model-size combinations: '+repr(pairs))
    keys=[(p['ramble_experiment'],str(p['repeat_index']),p['condition_id']) for p in plans]
    if len(set(keys))!=len(keys):raise RuntimeError('Duplicate runnable concrete experiment/repeat/condition keys')
    return keys


def validate_attempt_evidence(paths, expected):
    """Exact generated identities, ready env, real output and success marker."""
    paths=list(paths); require_completed_attempts(paths,minimum=len(expected))
    records=[json.loads(p.read_text()) for p in paths]
    actual=[(d['ramble_experiment'],str(d['repeat_index']),d['condition_id']) for d in records]
    if Counter(actual)!=Counter(expected):
        raise RuntimeError('Missing/duplicate/unexpected attempts: expected='+repr(expected)+' actual='+repr(actual))
    for p,d in zip(paths,records):
        env=d.get('observed',{}).get('software_environment',{})
        if env.get('state')!='ready' or env.get('package_manager',{}).get('source')!='common-base':
            raise RuntimeError('Ready Common Base environment evidence missing: '+str(p))
        artifact=p.parent/'outputs/result/result.json'
        if not artifact.is_file():raise RuntimeError('Benchmark output missing: '+str(artifact))
        result=json.loads(artifact.read_text())
        params=d['resolved']['parameters']
        if result.get('model')!=params['model'] or str(result.get('size'))!=str(params['size']):
            raise RuntimeError('Benchmark output belongs to a different condition: '+str(p))
        if (not math.isfinite(float(result.get('rate',float('nan')))) or float(result['rate'])<=0
                or result.get('setup_tool')!='bpce-demo-tool-ok'):
            raise RuntimeError('Invalid toy benchmark output: '+str(artifact))
        if 'BPCE_SMOKE_OK' not in (p.parent/'benchmark.log').read_text():
            raise RuntimeError('Benchmark success marker absent: '+str(p))
    return {'expected':len(expected),'observed':len(records),'identities':'matched','outputs':'validated',
            'scope':'functional toy benchmark, not scientific/GPU validity'}


def validate_ramble_analysis(workspace, expected):
    path=Path(workspace)/'results.latest.json'
    data=json.loads(path.read_text())
    rows=data.get('experiments',data.get('experiment',[]))
    matched=[]
    for name in sorted({key[0] for key in expected}):
        found=[r for r in rows if r.get('name')==name or str(r.get('name','')).endswith('.'+name)]
        if len(found)!=1:raise RuntimeError('Missing/ambiguous Ramble analysis for '+name)
        row=found[0]
        if row.get('EXPERIMENT_STATUS',row.get('RAMBLE_STATUS'))!='SUCCESS':
            raise RuntimeError('Ramble did not judge success for '+name)
        # Repeat summaries reuse the FoM name for stdev/variance/count. Those
        # values can legitimately be zero or 'NA'; they are not throughput.
        central_summaries = {'summary::mean', 'summary::min', 'summary::max'}
        values = [
            f.get('value')
            for context in row.get('CONTEXTS', [])
            for f in context.get('foms', [])
            if f.get('name') == 'toy_rate'
            and (not str(f.get('origin_type', '')).startswith('summary::')
                 or f.get('origin_type') in central_summaries)
        ]
        if not values or any(not math.isfinite(float(v)) or float(v)<=0 for v in values):
            raise RuntimeError('Missing/invalid toy_rate FoM for '+name)
        matched.append(name)
    return {'status':'passed','path':str(path),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'experiments':matched}

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('checkout',type=Path);p.add_argument('--output',type=Path,required=True)
    p.add_argument('--base-python',default='python3',help='Site example: declared Python inside the supplied Base')
    p.add_argument('--base-shell',default='bash',help='Site example: declared Bash inside the supplied Base')
    p.add_argument('--runtime-executable',default='apptainer',help='Site example: host Apptainer executable')
    p.add_argument('--host-shell',default='bash',help='Host shell for the native Benchpark setup.sh')
    p.add_argument('--worker-python',default=sys.executable,help='Host Python available on the execution node')
    p.add_argument('--base-sif',type=Path);p.add_argument('--run',action='store_true');p.add_argument('--timeout',type=int,default=2400)
    a=p.parse_args()
    if a.run and not a.base_sif:p.error('--run requires --base-sif')
    out=a.output.resolve();out.mkdir(parents=True,exist_ok=False)
    report={'schema_version':1,'source':str(a.checkout.resolve()),'stages':[],
            'container_generation':'not-run','container_runtime':'not-run','status':'RUNNING'}
    child_env = dict(os.environ)
    def call(label,cmd,expected=0,cwd=None):
        start=time.monotonic()
        r=subprocess.run([str(x) for x in cmd],capture_output=True,text=True,cwd=cwd,timeout=a.timeout,env=child_env)
        (out/(label+'.log')).write_text(r.stdout+'\n--- STDERR ---\n'+r.stderr)
        report['stages'].append({'name':label,'command':[str(x) for x in cmd], 'exit_code':r.returncode,'seconds':time.monotonic()-start})
        if (expected==0 and r.returncode!=0) or (expected!=0 and r.returncode==0):
            raise RuntimeError(label+' produced unexpected exit '+str(r.returncode)+
                               '; see '+str(out/(label+'.log'))+'\n'+r.stderr[-2400:])
        return r
    try:
        report['extension']=verify_installed_source(ROOT)
        if not (a.checkout/'.git').exists():raise ValueError('Provide a genuine git checkout (not a source-fixture directory)')
        # Do not install/upgrade anything implicitly in the user's environment.
        import importlib.util
        required = ('yaml', 'deepdiff')  # Other dependencies may be supplied by upstream bootstrap.
        missing = []
        for module in required:
            try: available = importlib.util.find_spec(module) is not None
            except ModuleNotFoundError: available = False
            if not available: missing.append(module)
        if missing:
            raise RuntimeError('Missing Benchpark dependencies: '+', '.join(missing)+
                               '. Install the target checkout requirements.txt in this Python first.')
        status=call('source-status',['git','-C',a.checkout.resolve(),'status','--porcelain']).stdout.strip()
        if status:
            raise RuntimeError('Source checkout has changes; use a clean source clone (not the old patched verify directory).')
        clone=out/'benchpark'
        call('clone',['git','clone','--no-hardlinks',a.checkout.resolve(),clone])
        report['benchpark_commit']=call('commit',['git','-C',clone,'rev-parse','HEAD']).stdout.strip()
        versions=clone/'checkout-versions.yaml'
        if versions.exists():report['pinned_dependencies']=yaml.safe_load(versions.read_text())
        cfg=create_config(clone,out/'config',out/'bootstrap')
        bp=[sys.executable,clone/'lib/main.py','-C',cfg]
        baseline_version=call('baseline-version',bp+['--version']).stdout
        # Uses native definitions. This initializes no Container runtime.
        system=out/'native-system'
        call('baseline-system',bp+['system','init','--dest='+str(system),'generic-x86'])
        call('baseline-experiment',bp+['experiment','init','--dest=native-before',system,'stream package_manager=user-managed'])
        before=yaml.safe_load((system/'native-before/ramble.yaml').read_text())
        call('baseline-spack-default',bp+['experiment','init','--dest=spack-before',system,'stream'])
        spack_before=yaml.safe_load((system/'spack-before/ramble.yaml').read_text())
        call('baseline-setup',bp+['setup',system/'native-before',out/'native-runs-before'])
        patch,records=make_patch(clone);patch_path=out/'core.patch';patch_path.write_text(patch)
        report['core_files']=records
        call('patch-check',['git','-C',clone,'apply','--check',patch_path])
        call('patch-apply',['git','-C',clone,'apply',patch_path])
        if call('patched-version',bp+['--version']).stdout!=baseline_version:
            raise RuntimeError('Benchpark version changed after patch')
        call('help',[sys.executable,clone/'lib/main.py','--help'])
        call('cer-help',bp+['cer','--help'])
        call('patched-system',bp+['system','init','--dest='+str(out/'native-system-after'),'generic-x86'])
        call('native-after',bp+['experiment','init','--dest=native-after',system,'stream package_manager=user-managed'])
        after=yaml.safe_load((system/'native-after/ramble.yaml').read_text())
        call('native-after-setup',bp+['setup',system/'native-after',out/'native-runs-after'])
        if normal(before)!=normal(after):
            raise RuntimeError('Native generated configuration differs beyond command/destination fields')
        call('patched-spack-default',bp+['experiment','init','--dest=spack-after',system,'stream'])
        spack_after=yaml.safe_load((system/'spack-after/ramble.yaml').read_text())
        if normal(spack_before)!=normal(spack_after):
            raise RuntimeError('Default Spack configuration changed')
        report['spack_default_config_equivalence']='passed'
        if a.base_sif:
            import platform
            arch={'aarch64':'arm64','arm64':'arm64','x86_64':'amd64'}.get(platform.machine())
            if arch is None: raise RuntimeError('Unsupported verifier host architecture')
            child_env['BPCE_CONFIG']=str(out/'catalogs.yaml')
            call('catalog-init',bp+['container','catalog','init',out/'catalog','--name','acceptance'])
            call('catalog-add',bp+['container','catalog','add',out/'catalog','--name','acceptance'])
            call('catalog-register',bp+['container','register','--catalog','acceptance',
                 '--name','pytorch-base','--release','release-a','--kind','sif','--source',a.base_sif.resolve(),
                 '--platform','linux/'+arch,'--accelerator','none','--python',a.base_python,'--shell',a.base_shell])
            container_system=out/'container-system'
            call('container-system',bp+['system','init','--dest='+str(container_system),'bpce-local',
                                       'image_cache='+str(out/'image-cache'),
                                       'runtime_executable='+a.runtime_executable,'worker_python='+a.worker_python])
            call('container-init',bp+['experiment','init','--dest=matrix',container_system,
                                     'common-base-smoke +container model=linear,mlp size=16,32 n_repeats=1'])
            call('container-tune',bp+['experiment','init','--dest=tuned',container_system,
                                      'common-base-smoke +container tune=inference-mode'])
            runs=out/'runs';call('container-setup',bp+['setup',container_system/'matrix',runs])
            # Re-running setup at the same destination MUST fail without deleting results.
            call('overwrite-denied',bp+['setup',container_system/'matrix',runs],expected=1)
            report['container_generation']='passed'
            if a.run:
                workspace=runs/'container-system/matrix/workspace'
                import shlex
                prefix='. '+shlex.quote(str(runs/'setup.sh'))+'; '
                base='ramble -P -D '+shlex.quote(str(workspace))
                call('ramble-setup',[a.host_shell,'-ec',prefix+base+' workspace setup'])
                expected=planned_attempts(workspace)
                report['planned_attempt_keys']=expected
                call('ramble-on',[a.host_shell,'-ec',prefix+base+' on'])
                records_before=list((workspace/'.benchpark-extensions/runs').rglob('cer.json'))
                report['first_run_evidence']=validate_attempt_evidence(records_before,expected)
                call('ramble-analyze',[a.host_shell,'-ec',prefix+base+' workspace analyze --formats json'])
                report['ramble_analysis']=validate_ramble_analysis(workspace,expected)
                # A second run must add attempts and retain every previous record.
                saved={str(p):p.read_bytes() for p in records_before}
                call('ramble-on-repeat',[a.host_shell,'-ec',prefix+base+' on'])
                if any(Path(p).read_bytes()!=v for p,v in saved.items()):raise RuntimeError('Old attempt changed')
                records_after=list((workspace/'.benchpark-extensions/runs').rglob('cer.json'))
                new_attempts=[p for p in records_after if str(p) not in saved]
                report['retry_evidence']=validate_attempt_evidence(new_attempts,expected)
                report['container_runtime']='passed'
        resolved={}
        for component in ('ramble','spack','spack-packages'):
            path=out/'bootstrap'/component
            if (path/'.git').exists():
                resolved[component]=call('resolved-'+component,['git','-C',path,'rev-parse','HEAD']).stdout.strip()
        report['resolved_bootstrap_commits']=resolved
        # Also prove that this new patch is reversible on the actual checkout.
        call('patch-reverse-check',['git','-C',clone,'apply','--reverse','--check',patch_path])
        report['native_config_equivalence'] = 'passed'
        report['status']='PASSED_SELECTED_STAGES'
    except Exception as e:
        report.update(status='FAILED',error_type=type(e).__name__,error=str(e))
        print(str(e),file=sys.stderr)
    finally:
        (out/'report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n')
    return 0 if report['status']=='PASSED_SELECTED_STAGES' else 1

if __name__=='__main__':sys.exit(main())
